
---
name: Auto lint & commit 🤖

on:
  push:
    branches:
      - main
env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

permissions: 
  contents: write
  
jobs:
  auto-lint-and-commit:
    name: Auto lint & commit 🤖
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.  
          # token: ${{ secrets.LINT_AND_COMMIT_PAT }}

      # - name: Use Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18.x'

      # - name: 📥 Monorepo install
      #   uses: ./.github/actions/yarn-nm-install
      #   with:
      #     cache-node-modules: true
      #     cache-install-state: true

      # - name: Run prettier
      #   run: yarn workspace @builder.io/root lint:fix

      # - name: Run eslint
      #   run: yarn workspace @builder.io/sdks lint

      # - name: "Import GPG key"
      #   id: import-gpg
      #   uses: crazy-max/ghaction-import-gpg@v6
      #   with:
      #     gpg_private_key: ${{ secrets.LINT_AND_COMMIT_GPG_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.LINT_AND_COMMIT_GPG_PASSPHRASE }}
      #     git_user_signingkey: true
      #     git_commit_gpgsign: true

      # - run: ./scripts/lint-and-commit.sh
      #   shell: bash
      #   env:
      #     PRIVATE_KEY: ${{secrets.LINT_AND_COMMIT_GPG_PRIVATE_KEY}}
      #     PUBLIC_KEY: ${{secrets.LINT_AND_COMMIT_GPG_PUBLIC_KEY}}
      #     KEY_ID: ${{ secrets.LINT_AND_COMMIT_GPG_KEY_ID }}
  
      - name: add changes
        run: |
          git config --global user.email "sami+builderbot@builder.io"
          git config --global user.name "builderio-bot"
          echo foo > bar.txt
          git add .
          git commit -m "Apply linting changes"
  

      # - run: git config --global credential.https://github.com.username builderio-bot
      # - run: git config --global credential.https://github.com.password $GH_ACCESS_TOKEN
      #   env:
      #     GH_ACCESS_TOKEN: ${{ secrets.LINT_AND_COMMIT_PAT }}
  
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.LINT_AND_COMMIT_PAT }}
          branch: main
    
      # - uses: stefanzweifel/git-auto-commit-action@v5
      #   id: auto-commit-action
      #   with:
      #     commit_message: Apply linting changes
      #     commit_author: "builderio-bot <sami+builderbot@builder.io>"
      #     commit_user_name: builderio-bot
      #     commit_user_email: sami+builderbot@builder.io
     
    
      # - name: "Run if changes have been detected"
      #   if: steps.auto-commit-action.outputs.changes_detected == 'true'
      #   run: echo "Committed linting changes."
    
      # - name: "Run if no changes have been detected"
      #   if: steps.auto-commit-action.outputs.changes_detected == 'false'
      #   run: echo "No linting changes to commit."
  
